// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorldCup2022_MVC.Contexts;

#nullable disable

namespace WorldCup2022_MVC.Migrations.KnockoutStage
{
    [DbContext(typeof(KnockoutStageContext))]
    [Migration("20221015125742_knockoutstage")]
    partial class knockoutstage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WorldCup2022_MVC.Models.KnockoutStage", b =>
                {
                    b.Property<int>("KnockoutStageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KnockoutStageId"), 1L, 1);

                    b.Property<string>("away")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("home")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KnockoutStageId");

                    b.ToTable("KnocoutStage");
                });
#pragma warning restore 612, 618
        }
    }
}
