SET IDENTITY_INSERT [WorldCup2022].[dbo].[Team] ON
INSERT INTO [WorldCup2022].[dbo].[Team]   (
       [teamId]
      ,[name]
      ,[picture]
      ,[placeInGroup]
      ,[placeInGlobalRanking]
)
VALUES
    (
        1,
        'Qatar',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/250px-Flag_of_Qatar.svg.png',
        'A1',
        50
    ),
    (
        2,
        'Ecuador',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/125px-Flag_of_Ecuador.svg.png',
        'A2',
        44
    ),
    (
        3,
        'Senegal',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/125px-Flag_of_Senegal.svg.png',
        'A3',
        18
    ),
    (
        4,
        'Netherlands',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/125px-Flag_of_the_Netherlands.svg.png',
        'A4',
        8
    ),
    (
        5,
        'England',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Flag_of_England.svg/125px-Flag_of_England.svg.png',
        'B1',
        5
    ),
    (
        6,
        'Iran',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/125px-Flag_of_Iran.svg.png',
        'B2',
        20
    ),
    (
        7,
        'United States',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/125px-Flag_of_the_United_States.svg.png',
        'B3',
        16
    ),
    (
        8,
        'Wales',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Flag_of_Wales.svg/125px-Flag_of_Wales.svg.png',
        'B4',
        19
    ),
    (
        9,
        'Argentina',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/125px-Flag_of_Argentina.svg.png',
        'C1',
        3
    ),
    (
        10,
        'Saudi Arabia',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/125px-Flag_of_Saudi_Arabia.svg.png',
        'C2',
        51
    ),
    (
        11,
        'Mexico',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/125px-Flag_of_Mexico.svg.png',
        'C3',
        13
    ),
    (
        12,
        'Poland',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Flag_of_Poland_%28normative%29.svg/125px-Flag_of_Poland_%28normative%29.svg.png',
        'C4',
        26
    ),
    (
        13,
        'France',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_France_%281794%E2%80%931815%2C_1830%E2%80%931974%2C_2020%E2%80%93present%29.svg/125px-Flag_of_France_%281794%E2%80%931815%2C_1830%E2%80%931974%2C_2020%E2%80%93present%29.svg.png',
        'D1',
        4
    ),
    (
        14,
        'Australia',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Australia.svg/125px-Flag_of_Australia.svg.png',
        'D2',
        38
    ),
    (
        15,
        'Denmark',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/125px-Flag_of_Denmark.svg.png',
        'D3',
        10
    ),
    (
        16,
        'Tunisia',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/125px-Flag_of_Tunisia.svg.png',
        'D4',
        30
    ),
    (
        17,
        'Spain',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/125px-Flag_of_Spain.svg.png',
        'E1',
        7
    ),
    (
        18,
        'Costa Rica',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Costa_Rica_%28state%29.svg/125px-Flag_of_Costa_Rica_%28state%29.svg.png',
        'E2',
        31
    ),
    (
        19,
        'Germany',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/125px-Flag_of_Germany.svg.png',
        'E3',
        11
    ),
    (
        20,
        'Japan',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/125px-Flag_of_Japan.svg.png',
        'E4',
        24
    ),
    (
        21,
        'Belgium',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Belgium.svg/125px-Flag_of_Belgium.svg.png',
        'F1',
        2
    ),
    (
        22,
        'Canada',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/125px-Flag_of_Canada_%28Pantone%29.svg.png',
        'F2',
        41
    ),
    (
        23,
        'Morocco',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/125px-Flag_of_Morocco.svg.png',
        'F3',
        22
    ),
    (
        24,
        'Croatia',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/125px-Flag_of_Croatia.svg.png',
        'F4',
        12
    ),
    (
        25,
        'Brazil',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/125px-Flag_of_Brazil.svg.png',
        'G1',
        1
    ),
    (
        26,
        'Serbia',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/125px-Flag_of_Serbia.svg.png',
        'G2',
        21
    ),
    (
        27,
        'Switzerland',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Flag_of_Switzerland_%28Pantone%29.svg/125px-Flag_of_Switzerland_%28Pantone%29.svg.png',
        'G3',
        15
    ),
    (
        28,
        'Cameroon',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/125px-Flag_of_Cameroon.svg.png',
        'G4',
        43
    ),
    (
        29,
        'Portugal',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/125px-Flag_of_Portugal.svg.png',
        'H1',
        9
    ),
    (
        30,
        'Ghana',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/125px-Flag_of_Ghana.svg.png',
        'H2',
        61
    ),
    (
        31,
        'Uruguay',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/125px-Flag_of_Uruguay.svg.png',
        'H3',
        14
    ),
    (
        32,
        'South Korea',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/125px-Flag_of_South_Korea.svg.png',
        'H4',
        28
    );
    