// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorldCup2022_MVC.Contexts;

#nullable disable

namespace WorldCup2022_MVC.Migrations.GroupStage
{
    [DbContext(typeof(GroupStageContext))]
    [Migration("20220817165037_groupstage")]
    partial class groupstage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WorldCup2022_MVC.Models.GroupStage", b =>
                {
                    b.Property<int>("groupStageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("groupStageId"), 1L, 1);

                    b.Property<string>("away")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("home")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("groupStageId");

                    b.ToTable("GroupStage");
                });
#pragma warning restore 612, 618
        }
    }
}
